### ISSUE TITLE
Lexer Incomplete

### ISSUE THREAD

**Issue by neomannskar** [Totem-Studios/lotus#17]
The Lexer is not yet completed but it is under its way. There is not yet any support for UTF-8 characters in the lexer, something that will be get added later however currently gets handled as "unsupported characters."

**Comment by pontushenriksson** [comment]
The lexer is now implemented and includes some features but not all the features we are going to work on in the future so because of this, this issue will be deleted and marked as completed to make space for future more specific issues with the lexer. Don't hesitate to refer to this issue in the future.
